project_id = "fglxrbmjteqircyweirf"

[functions.generate-diet-plan]
verify_jwt = true

[functions.seed-workout-data]
verify_jwt = true

[functions.seed-gym-data]
verify_jwt = true

[functions.seed-membership-data]
verify_jwt = true

[functions.send-application-email]
verify_jwt = true